# Generated by Django 3.2.4 on 2021-08-23 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resulthistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result', to=settings.AUTH_USER_MODEL),
        ),
    ]
